var TB303 = window.TB303 = window.TB303 || {};

TB303.constants = {
  NOTES: ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'],
  STEPS: 16,
  PATTERNS: 16,

  DEFAULT_BPM: 120,
  DEFAULT_CUTOFF: 800,
  DEFAULT_RESONANCE: 0.5,
  DEFAULT_ENV_MOD: 0.5,
  DEFAULT_DECAY: 200,
  DEFAULT_ACCENT: 0.7,
  DEFAULT_DISTORTION: 0.2,
  DEFAULT_TUNE: 0,

  MIN_CUTOFF: 20,
  MAX_CUTOFF: 8000,
  MIN_RESONANCE: 0.5,
  MAX_RESONANCE: 8.0,
  MIN_DECAY: 10,
  MAX_DECAY: 2000,
  MIN_ENV_MOD: 0,
  MAX_ENV_MOD: 1,
  MIN_ACCENT: 0,
  MAX_ACCENT: 1,
  MIN_DISTORTION: 0,
  MAX_DISTORTION: 1,
  MIN_TUNE: -12,
  MAX_TUNE: 12,
};
